/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#34C759",
        secondary: "#E5E5EA",
        background: "#FFFFFF",
        surface: "#F2F2F7",
        accent: "#30D158",
        border: "#C7C7CC",
        error: "#FF453A",
        success: "#32D74B",
        warning: "#FFD60A",
        muted: "#8E8E93",
        black: "#000000",
        white: "#FFFFFF",
      },
      fontFamily: {
        sans: [
          'SF Pro Text',
          'Inter',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        heading: [
          'SF Pro Display',
          'Inter',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        md: "17px",
        lg: "18px",
        xl: "20px",
        '2xl': "24px",
        '3xl': "30px",
        '4xl': "36px",
        '5xl': "48px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(0,0,0,0.05)",
        DEFAULT: "0 1px 3px rgba(0,0,0,0.1)",
        md: "0 4px 6px rgba(0,0,0,0.1)",
        lg: "0 10px 15px rgba(0,0,0,0.1)",
        '2xl': "0 25px 50px rgba(0,0,0,0.25)",
        focus: "0 0 0 3px rgba(52, 199, 89, 0.4)",
      },
      spacing: {
        '5px': '5px',
        '7px': '7px',
        '18px': '18px',
        '22px': '22px',
        '72': '18rem',
        '84': '21rem',
        '96': '24rem',
      },
      borderRadius: {
        none: "0",
        sm: "4px",
        DEFAULT: "10px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        full: "9999px",
      },
      lineHeight: {
        tight: 1.2,
        snug: 1.375,
        normal: 1.5,
        relaxed: 1.625,
        loose: 2,
      },
      screens: {
        xs: '320px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
      },
    },
  },
  plugins: [],
}
